# Generated by Django 6.1 on 2026-08-17 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Only English letters and apostrophes are allowed.', regex="^[A-Za-z]+(?:'[A-Za-z]+)*$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Only English letters and apostrophes are allowed.', regex="^[A-Za-z]+(?:'[A-Za-z]+)*$")]),
        ),
    ]
