# Generated by Django 6.1 on 2026-08-16 09:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="unique_events",
        ),
        migrations.AddField(
            model_name="event",
            name="max_members",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(10000)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("organizer", "title", "start_date", "location"),
                name="unique_events",
            ),
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="event",
            name="members",
        ),
        migrations.AddField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
