# Generated by Django 6.1 on 2026-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_event_unique_events_event_max_members_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_date", "title"]},
        ),
        migrations.AddField(
            model_name="event",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
