# Generated by Django 6.1 on 2026-08-17 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_event_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='max_members',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
